export const authConstants = {
    // Login Constants
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    
    // Logout Constants
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    
    // Check Authentication
    CHECK_AUTH_REQUEST: 'CHECK_AUTH_REQUEST',
    CHECK_AUTH_SUCCESS: 'CHECK_AUTH_SUCCESS',
    CHECK_AUTH_FAILURE: 'CHECK_AUTH_FAILURE',
    
    // Clear Errors
    CLEAR_AUTH_ERRORS: 'CLEAR_AUTH_ERRORS',
    
    // User Update
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  };